#!/bin/bash

MACROFILE="POT1000.mac"
nruns=159
proccnt=0
WORKDIR=`pwd`
for (( i=1; i<=nruns; i++))
do
  outfile="run${i}.sh"
  echo -e "#!/bin/bash\n" > $outfile
  echo -e "#SBATCH -n 16" >> $outfile
echo -e "#SBATCH --ntasks-per-node 16" >> $outfile
  echo -e "# This file is automatically generated by generate_runscripts.sh." >> $outfile
  echo -e "WORKDIR=${WORKDIR}\n" >> $outfile
  # Here the variable i in the following sentence is the RANDOM SEED in the simulation!
  echo -e '$WORKDIR'"/../../../build/exampleB1 "'$WORKDIR'"/../../run${i}.mac $i" >> $outfile
  proccnt=$((proccnt+1))
done

echo "$proccnt macro files are generated."
