#!/bin/bash

#SBATCH -n 16
#SBATCH --ntasks-per-node 16
# This file is automatically generated by generate_runscripts.sh.
WORKDIR=/cluster/home/jhb0089/VacuumChamberSim/scripts/batch/runscripts

$WORKDIR/../../../build/exampleB1 $WORKDIR/../../run4.mac 4
